# This is the main ansible-playbook

# Run using:
# ansible-playbook site.yml -i environments/vm/inventory

- name: Configuration for all nodes
  hosts: all
  sudo: True
  tags: common
  gather_facts: no
  remote_user: "{{ ansible_remote_user }}"

  roles:
  - common


# Applies the "example" role to the hosts in the "example" group
# In the default inventory the "example" group does not exists, nor are there hosts named "example". Therefore the
# example role is not applied to any hosts
- name: Apply role "example" to hosts in group "example"
  hosts: example
  sudo: True
  tags: example
  gather_facts: no
  remote_user: "{{ ansible_remote_user }}"

  roles:
  - example
# - some_other_role