# Vagrant configuration file for a development VM
# Works with vmware fusion and virtual box providers

Vagrant.configure("2") do |config|

    # The VM Image to use. Find others at: http://vagrantcloud.com
    # Note: The "nocm" version of this box does not have any puppet software installed
    config.vm.box = "puppetlabs/ubuntu-14.04-64-nocm"

    # VM: "local-sympa"
    config.vm.define "local-sympa" do |conf|
        conf.vm.hostname = "local-sympa"
        # Give it a fixed IP
        conf.vm.network "private_network", ip: "192.168.66.66", :netmask => "255.255.255.0"
        conf.vm.provider "vmware_fusion" do |v|
            v.vmx["memsize"] = "1024"
        end
        conf.vm.provider "virtualbox" do |v|
            v.memory = 1024
        end
    end

#    # VM: "dev-vm2"
#    config.vm.define "dev-vm2" do |conf|
#        conf.vm.hostname = "dev-vm2"
#        # Give it a fixed IP
#        conf.vm.network "private_network", ip: "192.168.66.67", :netmask => "255.255.255.0"
#        conf.vm.provider "vmware_fusion" do |v|
#            v.vmx["memsize"] = "1024"
#        end
#        conf.vm.provider "virtualbox" do |v|
#            v.memory = 1024
#        end
#    end

    config.vm.provision "ansible" do |ansible|
        # Groups to add to the Ansible inventory file generated by Vagrant
        # For use by ansible-playbook later.
        # These are not used by provision.yml

        ansible.groups = {
          "sympa" => ["local-sympa"],
        }
        ansible.playbook = "provision-vagrant-vm.yml"
        #ansible.verbose = "vvvv" # For troubleshooting ansible connection problems
    end

end
