---

- name: Create sympa directories
  file: dest={{ item }} state=directory mode=755 owner=sympa
  with_items: ["{{ install_prefix }}/{{ sympa.install_dir_name }}", "{{ install_prefix }}/{{ sympa.install_dir_name }}/src"]

- name: Include retrieving sources from tar.gz task if needed
  import_tasks: get_sources_from_targz.yml
  when: not sympa.install_from_repository

- name: Include retrieving sources from repository if needed.
  import_tasks: get_sources_from_repo.yml
  when: sympa.install_from_repository
